version: "3.1"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sample-php-app
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../www:/var/www

  nginx:
    image: nginx:1.23
    container_name: sample-nginx-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../www:/var/www
      - ./nginx:/etc/nginx/conf.d
#
#
#   db:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#     volumes:
#       - mysql-data:/var/lib/mysql

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

# volumes:
#   mysql-data:
