<?php
echo "<a href='echo_print_variable.php'>echo, print, variables</a><br/>";
echo "<br/>";
echo "<a href='data_types.php'>data types, casting</a><br/>";
echo "<br/>";
echo "<a href='more_boolean.php'>more boolean</a><br/>";
echo "<br/>";
echo "<a href='more_int.php'>more integer</a><br/>";
echo "<br/>";
echo "<a href='more_float.php'>more float</a><br/>";
echo "<br/>";
echo "<a href='more_string.php'>more string</a><br/>";
echo "<br/>";
echo "<a href='null.php'>null</a><br/>";
echo "<br/>";
echo "<a href='array.php'>array</a><br/>";
echo "<br/>";
echo "<a href='control.php'>control structure</a><br/>";
echo "<br/>";
echo "<a href='loop.php'>loop</a><br/>";
echo "<br/>";
echo "<a href='switch_match.php'>switch and match</a><br/>";
echo "<br/>";
echo "<a href='include_file.php'>include file</a><br/>";
echo "<br/>";
echo "<a href='function.php'>function</a><br/>";
echo "<br/>";
echo "<a href='static.php'>scope & static variables</a><br/>";
echo "<br/>";
echo "<a href='variable_anonymous_callable_closure_arrow_function.php'>variable, anonymous, callable, closure, arrow functions</a><br/>";
echo "<br/>";
echo "<a href='date_time.php'>date & time</a><br/>";
echo "<br/>";
echo "<a href='array_functions.php'>array's functions</a><br/>";
echo "<br/>";
echo "<a href='php_configuration.php'>php configuration</a><br/>";
echo "<br/>";
echo "<a href='error_handling.php'>error handling</a><br/>";
echo "<br/>";
echo "<a href='file_system.php'>file system</a><br/>";
echo "<br/>";
echo "<a href='miniproject/index.php'>mini project</a><br/>";
?>